name: 'dbt_training'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# --------------------------------------------------------------------
# CONFIGURACIÓN DE MODELOS
# --------------------------------------------------------------------
models:
  dbt_training:
    +query_tag: 'dbt_course'

    # Materialización por defecto (puede cambiarse por modelo individual)
    +materialized: table

    # Ejemplo: subcarpetas opcionales
    # staging:
    #   +materialized: view

    # Añadimos metadatos por defecto (útil para Snowflake y auditoría)
    +persist_docs:
      relation: true
      columns: true

    # Etiqueta de warehouse para modelos transform
    +snowflake_warehouse: 'TRANSFORMING_S'

# --------------------------------------------------------------------
# DEPENDENCIAS DE PAQUETES (dbt_utils)
# --------------------------------------------------------------------
# Este bloque indica que este proyecto depende de dbt_utils
# (el paquete que usamos para generar surrogate keys)
packages-install-path: "dbt_packages"
