version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: customers
        description: Each record in this table represents a customer in our ecommerce application.
        columns:
          - name: id
            description: '{{ doc("customer_id") }}'
            
      - name: orders_us # This no longer has an orders alias
        description: Each record in this table represents an order in our ecommerce store in the US

      - name: orders_de # This is new
        description: Each record in this table represents an order in our ecommerce store in Germany

      - name: orders_au # This is new
        description: Each record in this table represents an order in our ecommerce store in Australia
    
      - name: orders_au_duped # This is new
        description: Each record in this table represents an order in our ecommerce store in Australia


      - name: deliveries
        description: Each record in this table represents an order delivery in our ecommerce application.

  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses

  - name: stripe
    database: raw
    tables:
      - name: payments